### ISSUE TITLE
Regarding the logging inside from Virtual Private Cloud (amazon)

### ISSUE THREAD

**Issue by thapakazi** [rapid7/le_ruby#63]
I am trying to push the logs from the my apps which are deployed inside the VPC where we filter the inbound/outbound ports.

We have not allowed the app to have outbound connection to **10000 port**, is it the reason we are  unable to send logs to the logentries servers ? My knowledge till this is like, we do some post request to your (logentries) api at either **443 or 80** . I know i am missing something, Someone please educate me :neckbeard: 
![screenshot-20170201-18 23 12](https://cloud.githubusercontent.com/assets/1695906/22507142/27d05e22-e8ac-11e6-9d56-bfce9f1cc746.png)

**Comment by rjacobs-r7** [comment]
The Ruby library connects to _api.logentries.com_ on port _10000_ using a TCP socket by default, or optionally a UDP socket. This provides less overhead than using the HTTP API.

**Comment by thapakazi** [comment]
thanks for reply, I will test with _10000_ tcp port first. 

Also is ssl also enforced forcibly @rjacobs-r7 ?

**Comment by rjacobs-r7** [comment]
@thapakazi SSL is optional

**Comment by udangel-r7** [comment]
Can we please stop using API.le.com for data ingestion abd switch to data.le.com. I thought we adjusted everything

**Comment by rjacobs-r7** [comment]
@udangel-r7 Not the Ruby API 😬
